version: "3.8"

services:
    php:
        build:
            context: ./php # Indica onde está o arquivo Dockerfile
            dockerfile: Dockerfile
        container_name: php # Apelido para o container
        volumes:
            - ./src:/var/www/html/ # Irá copiar o conteúdo da pasta src para o container
        ports: # Mapear as portas para ficarem visiveis na máquina host
            - "80:80"
            - "443:443"
        links: # Criar conexão com o container do banco de dados
            - mysql
            - postgres

    # phpmyadmin:
    #     build:
    #         context: ./phpmyadmin
    #         dockerfile: Dockerfile
    #     container_name: phpmyadmin
    #     restart: always
    #     volumes:
    #         - /sessions
    #     ports:
    #         - "8080:80"
    #     links:
    #         - mysql
    #     environment:
    #         - PMA_ARBITRARY=1 # Habilitando a opção para inserir host no login

    postgres:
        image:  postgres
        container_name: postgres
        restart: always
        ports:
            - "5432:5432"
        environment:
            - DATABASE_HOST=0.0.0.0
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
    mysql:
        image: mysql # A versão 8.0 está com instabilidades
        container_name: mysql
        restart: always # Por padrão o Docker não reinicia o container, vamos mudar isso.
        image: mysql
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: test
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test 
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default

    mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        container_name: mssql
        restart: always # Por padrão o Docker não reinicia o container, vamos mudar isso.
        ports:
            - '1433:1433'
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=Secret1234
        volumes:
            - './data:/var/opt/mssql'
volumes:
  persistent:
#-----------------------------------------------------------------------------------------------------------------------------------------------#
# Caso dê problema para seu PHP conectar ao banco, use a versão 5.7 do MySQL ou faça o tutorial abaixo:
# docker container exec -it mrb-mysql bash
# mysql -u root -p
# ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY 'root';
# ALTER USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'root';
# ALTER USER 'default'@'%' IDENTIFIED WITH mysql_native_password BY 'secret';
#-----------------------------------------------------------------------------------------------------------------------------------------------#

